// Copyright (c) 2018-2021 The MobileCoin Foundation

//! MobileCoin transaction data types, transaction construction and validation
//! routines

#![no_std]

// TODO: Re-enable when the impl generated by derive(Oneof) includes the
// necessary docs: https://github.com/tokio-rs/prost/issues/237
//#![deny(missing_docs)]

extern crate alloc;

#[cfg(test)]
#[macro_use]
extern crate std;

#[macro_use]
extern crate lazy_static;

pub mod amount;
pub mod blockchain;
pub mod constants;
pub mod domain_separators;
pub mod encrypted_fog_hint;
pub mod fog_hint;
pub mod membership_proofs;
pub mod memo;
pub mod onetime_keys;
pub mod quorum_set;
pub mod range_proofs;
pub mod ring_signature;
pub mod token;
pub mod tx;
pub mod tx_error;
pub mod validation;

#[cfg(test)]
pub mod proptest_fixtures;

pub use self::{
    amount::{Amount, AmountError, Commitment, CompressedCommitment, MaskedAmount},
    blockchain::*,
    memo::{EncryptedMemo, MemoError, MemoPayload},
    quorum_set::{QuorumNode, QuorumSet, QuorumSetMember, QuorumSetMemberWrapper},
    token::{tokens, Token, TokenId},
    tx::*,
    tx_error::{NewMemoError, NewTxError, ViewKeyMatchError},
};
